### ISSUE TITLE
SoundJs with preloadjs fails when sound already cached in browser

### ISSUE THREAD

**Issue by bknill** [CreateJS/SoundJS#283]
I'm registering the sound in Preload and playing the sound very soon afterwards. 
If I clear the cache it plays fine, 

If I reload the page I get this error

```
soundjs.min.js:18 Uncaught TypeError: Cannot read property 'length' of null
    at WebAudioPlugin.a._handlePreloadComplete (soundjs.min.js:18)
    at soundjs.min.js:17
    at a._dispatchEvent (soundjs.min.js:17)
    at a.dispatchEvent (soundjs.min.js:17)
    at a._sendComplete (soundjs.min.js:17)
    at a.b._handleAudioDecoded (soundjs.min.js:18)
    at AudioContext.<anonymous> (soundjs.min.js:17)
```

Any clues what might cause it?

**Comment by lannymcnie** [comment]
There is an issue where the list of early-created sounds was being cleaned up improperly, which I have corrected. I also put in some error-handling which will prevent this particular error - however I am not entirely sure it will prevent whatever is causing the problem you posted.

I have pushed the fix to GitHub, and will build new NEXT libs shortly. I might sneak this change into the 1.0.x that is getting posted to the CDN.

If you are able to, I would appreciate a sanity test of the fix, and if it still persists, or there is other odd behaviour, a simple test case would be awesome.

Thanks!

**Comment by weituotian** [comment]
@lannymcnie not work!

**Comment by tangbj** [comment]
I'm still having this issue with the next version. Is there something I need to be doing?

**Comment by jfraboni** [comment]
Same, still experiencing this issue.

**Comment by nguyenhuutinh** [comment]
try this 			
`createjs.Sound.removeAllSounds();`
